### PR TITLE
Fix unicode characters handling

### LINKED ISSUE #59: Weird parsing of unicode characters
Given the following JSON:

```json
{
  "errors": [
    {
      "message": "Argument \u0022input\u0022 has an invalid value: ...."
    }
  ]
}
```

(for some reason a mink driver is returning this instead of `\"`...)

With `json_decode()` you will get:

```
{#4
  +"errors": array:1 [
    0 => {#5
      +"message": "Argument "input" has an invalid value: ...."
    }
  ]
}
```

However with `JsonParser` you will get:

```
{#17
  +"errors": array:1 [
    0 => {#16
      +"message": "Argument &#x22;input&#x22; has an invalid value: ...."
    }
  ]
}
```

Any idea of how this could be fixed?

### PR DESCRIPTION
**Pull request by theofidry**
Closes #59

I'm not an expert at this so I'm not sure this is the best way to handle this case to be honest. It's also a bit weird to use `json_decode` there but I've picked that solution as alternatives suggested the use of `mb_string` and I preferred to avoid a dependency on an extension at this point.

### CODE REVIEW

File: src/Seld/JsonLint/JsonParser.php [hunk 1]
```diff
@@ -450,6 +450,10 @@ private function performAction(stdClass $yyval, $yytext, $yyleng, $yylineno, $yy
 
     private function stringInterpolation($match)
     {
+        if (strpos($match[0], '\u') === 0) {
```
Comment (stof) [inline src/Seld/JsonLint/JsonParser.php]: I would move that inside the default, to avoid doing that string scanning for all cases matched by the `switch` case

Comment (theofidry) [reply src/Seld/JsonLint/JsonParser.php]: good point 👍

**Comment by stof** [comment]
also, is `\u0022` the only one failing the `html_entity_decode` code path ? If yes, a simpler solution is to put that case in the switch.

**Comment by theofidry** [comment]
@stof I'm not quite sure. It appears to be working fine for some emojis for example, but I'm unable to give an exhaustive list of what is working and what is not. However this begs the question, why `html_entity_decode()` is failing on this one if it handles fine others?

**Comment by Seldaek** [comment]
It seems actually the issue is merely with passing no flag to html_entity_decode, `html_entity_decode('&#x22;', ENT_QUOTES, 'UTF-8')` works fine for example. As per https://www.php.net/html_entity_decode ENT_QUOTES converts all quotes, which is probably what we want. Can you confirm and if so tweak the PR?

**Comment by theofidry** [comment]
Works fine!

**Comment by Seldaek** [comment]
Great, thanks :)
